spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/devlink?serverTimezone=Asia/Seoul&useUnicode=true
    username: root
    password: manager

    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
      open-in-view: false
      show-sql: true
      database-platform: org.hibernate.dialect.MariaDBDialect